### ISSUE TITLE
denyWriteAndDelete => cannot view container apps log stream

### ISSUE THREAD

**Issue by vRune4** [Azure/deployment-stacks#202]
**Describe the bug**
I tried switching to deployment stacks in my workflow, and after deploying my user (Owner role member) cannot view my container app's log stream. (Says "Unauthorized")

**To Reproduce**
1. Deploy container app
2. Use the following paramters:
```
        uses: azure/bicep-deploy@v1
        with:
          operation: create
          type: deploymentStack
          name: ${{ inputs.service-name }}
          scope: resourceGroup
          resource-group-name: ${{ env.RESOURCE_GROUP }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          template-file: infra/main.bicep
          parameters-file: ${{ steps.param-file.outputs.bicepparamfile }}
          action-on-unmanage-resources: delete
          deny-settings-mode: denyWriteAndDelete
```
3. View the container app's log stream

**Expected behavior**
Should be able to view the log stream

**Screenshots**
![Image](https://github.com/user-attachments/assets/ce26cb89-b97d-4a1c-b201-1779afa2fed2)

**Additional context**
This looks iffy:
![Image](https://github.com/user-attachments/assets/a7b403bd-99b6-4d17-8d13-20f14e256d77)
