### ISSUE TITLE
Second deployment of managed sql instance triggers instance rescaling

### ISSUE THREAD

**Issue by vRune4** [Azure/deployment-stacks#217]
**Describe the bug**
On the second deployment, using stacks, my SQL Managed Instance says it is scaling.

**To Reproduce**
1. Modify existing IaC project to use deployment stacks
2. Deploy once... (all good!)
3. Deploy again...

At this point it starts scaling the SQL Managed Instance, an operation that can take an hour+. (my first attempt even failed at the end, I am currently awaiting my second attempt)

**Expected behavior**
The deployment should just run like normal. As no changes to any resource has been made, it should finish within a few minutes.

**Screenshots**

![Image](https://github.com/user-attachments/assets/6cc69c3d-f288-40af-a63a-8cbfd473bdda)

![Image](https://github.com/user-attachments/assets/19e3d9aa-61e9-464d-b749-b18bb3faa4d6)

**Server Debugging Information**
Correlation ID: 6586f94f-2415-4332-b48f-ecb2814c749c and 4d1ed1e6-03e6-43fb-9e71-5367b5a1be0a
Tenant ID: c166b9c4-5053-4eec-9665-aba0782d0804
Timestamp of issue (please include time zone): 08:00 UTC
Data Center (eg, West Central US, West Europe): Norway East

**Additional context**
I have been switching to deployment stacks in my smaller bicep projects, and now I thought the time had come to use stacks in our main project.

My github workflow was changed to:
```yaml
      - name: 🚀 Deploy to ${{inputs.environment}} environment
        uses: azure/bicep-deploy@v2
        with:
          type: deploymentStack
          name: ${{inputs.environment}}
          operation: create
          scope: subscription
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          location: Norway East
          template-file: ./main.bicep
          action-on-unmanage-resources: delete
          deny-settings-mode: none 
          parameters-file: main.${{inputs.environment}}.bicepparam
          parameters: '{ "dbAdminUserLogin": "${{secrets.AD_ADMIN_LOGIN}}", "dbAdminUserSid":"${{secrets.AD_ADMIN_SID}}", "rsAdminUser":"${{secrets.RS_ADMIN_USER}}", "rsAdminPassword":"${{secrets.RS_ADMIN_PASSWORD}}"}'
```

The first deployment went extremely well.... But the second deployment (no change in between) failed.
